config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/jobs')
  resources :jobs, only: [:new, :create, :show, :index] do    
    resources :job_applications, only: [:create, :new, :index]
  end    
  resource :session, only: [:new, :reate, :destroy]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  poster_id   :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Job < ApplicationRecord

    validates :description, :title, :poster_id, presence: true

    
    belongs_to :poster,
        foreign_key: :poster_id,
        class_name: :User

    has_many :applies,
        foreign_key: :job_id,
        class_name: :JobApplication
    
    

end

app/models/job_application.rb
# == Schema Information
#
# Table name: applications
#
#  id         :integer          not null, primary key
#  job_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class JobApplication < ApplicationRecord

    

    belongs_to :user,
        foreign_key: :user_id,
        class_name: :User 
    
    belongs_to :job,
        foreign_key: :job_id,
        class_name: :Job  
        
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

    validates :email, :password_digest, :session_token, presence: true
    validates :email, uniqueness: true
    validates :password, length: { minimum: 6}, allow_nil: true
    attr_reader :password

    has_many :posted_jobs,
        foreign_key: :poster_id,
        class_name: :Job

    has_many :applied_jobs,
        foreign_key: :user_id,
        class_name: :JobApplication
    
    after_initialize :ensure_session_token
    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        user && user.is_password?(password) ? user : nil 
    end 

    def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)
    end 

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password) 
    end 

    def reset_session_token
        generate_unique_session_token
        save!
        self.session_token
    end 

    def ensure_session_token 
        generate_unique_session_token unless self.session_token
    end 

    def new_session_token 
        SecureRandom.urlsafe_base64
    end
    

    def generate_unique_session_token
        self.session_token = new_session_token 
        while User.find_by(session_token: self.session_token)
            self.session_token = new_session_token 
        end 
        self.session_token 
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # protect_from_forgery with: :exception
    skip_before_action :verify_authenticity_token
    helper_method :current_user, :logged_in? 

    private 

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end
    
    def logged_in?
        !!current_user
    end 
    
    def login(user)
        user.reset_session_token 
        session[:session_token] = user.session_token
        @current_user = user 
    end 

    def logout 
        current_user.reset_session_token
        session[:session_token] = nil 
        @current_user = nil 
    end 

    def require_logged_in 
        unless current_user
            render ["must log in"]
        end 
    end 
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController

    def create
        # p params 
        @job_application =  current_user.applied_jobs.new
        user_id = current_user.id
        # job_id = Job.find_by_id(params[:id])
        @job = Job.find_by(id: params[:job_id])
        
        @job_application.user_id = user_id  
        @job_application.job_id = @job.id
        
        # debugger
        if @job_application.save 
            redirect_to users_url
        else 
            debugger
            flash.now[:errors] = @job_application.errors.full_messages 
            render :new 
        end  

        
    end     

    def index 
        @jobs = JobApplication.find_by(poster_id: current_user.id).as_json
        @replies =  @jobs.map do |job|
            User.find(job.user_id)
        end    
        render :index
    end 
    
    
    def new 
        @job_application = JobApplication.new 
        render :new 
    end     

    private 
    def job_app_params 
        params.require(:job_application).permit(:user_id, :job_id)
    end     
end    

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index 
        @jobs = Job.all 
        render :index
    end    

    def show 
        @job = Job.find(params[:id])
        render :show
    end     

    def new 
        @job = Job.new 
        render :new 
    end     

    def create 
        @job = Job.new(job_params)
        @job.poster_id = current_user.id
        if @job.save 
            redirect_to job_url(@job)
        else 
            flash.now[:errors] = @job.errors.full_messages 
            render :new 
        end    
    end    

    private 
    
    def job_params 
        params.require(:job).permit(:title, :description)
    end   
end    

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

   
    def create 
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if user.nil?
            flash.now[:errors] = ["Incorrect password/email"]
            render :new 
        else 
            login(user)
            redirect_to jobs_url 
        end     
    end  

    def destroy 
        logout
        redirect_to new_session_url 
    end    

    def new 
        render :new 
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            redirect_to jobs_url 
        else      
            flash.now[:errors] = @user.errors.full_messages 
            render :new 
        end     
    end    

    def index 
        @my_jobs = Job.find_by(poster_id: current_user.id).as_json 

        @my_jobs_applicants = @my_jobs.each do |my_job|
            my_job.applies
        end    
       
        
        render :index
    end
    
    
    def show
        if !current_user 
            render :new
        end
        @job_applications = current_user.applied_jobs.as_json

        @my_applied_jobs = @job_applications.map do |job|
            Job.find_by(id: job["id"]).as_json
        end     
        
        render :show
        
    end    

    def new 
        @user = User.new 
        render :new 
    end    
    
    private 
    def user_params 
        params.require(:user).permit(:password, :email)
    end     
end     

app/views/job_applications/new.html.erb
<section>
    <div>
    <form action="<%= job_job_applications_url %>" method="post">
        <h2><%= @job.title %></h2>
        <input type="submit" description="Apply">
    </form>
    </div>
</section>

app/views/jobs/index.html.erb
<section>
    
    
    <h1>All Job Postings</h1>
    <% Job.all.each do |job| %>
        <div>
        <h4><%= job.title %></h4>
        <p><%=  job.description %></p>
        <a href="<%= job_url(job)%>">Job</a>
        </div>
    <% end %>
    <h1>Your Job Postings </h1>
    <% current_user.posted_jobs.each do |posted|%>
        <%= posted.as_json["title"] %>
        <br />
        <%= posted.as_json["description"] %>
        <br />
        <h4>Users Who Have Applied To this role</h4>
        <% posted.applies.each do |apply| %>
            <% user = User.find(apply[:user_id])%>
            <%= user["email"]%>
        <% end %>
    <% end %>
</section>

app/views/jobs/new.html.erb
<section>
    <div>
        <h1>Post A Job</h1>
        <form action="<%= jobs_url%>" method="post">
            <label for="job_title">Job Title</label>
            <input type="text"
                name="job[title]"
                id="job_title"
                value="<% @job.title %>"
            >
            
            <label for="job_description">Job Description</label>
            
            <input type="text"
                name="job[description]"
                id="job_description"
                value="<% @job.description %>"
                >
            <br />
            <input type="submit">
        </form>
        <a href="<%= jobs_url %>">Return To All Jobs</a>
    </div>
</section>

app/views/jobs/show.html.erb
<section>
    <div>
        <form action="<%= job_job_applications_url(job_id: @job.id) %>" method="post">
            
            <h2><%= @job.title %></h2>
            <p><%= @job.description %><p>
            <% my_bool = false%>
             <% current_user.applied_jobs.each do |applied_job|%>
                
                <% if @job.id == applied_job.job_id%>
                    <% my_bool = true%>
                <% end %>
            
            <% end %>


            <% if !my_bool %>
                <input type="submit">Apply Now
            <% else %>
                <p>Already Applied</p>
            <% end %>

            <p><a href="<%= jobs_url %>" >Back to job page<a></p>
         </form>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fountain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user%>
        <a href="<%= new_user_url%>">Sign Up</a>
        <br />
        <a href="<%= new_session_url%>">Sign In</a>
    <% else %>
        <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Logout">
      </form>
        <a href="<%= new_job_url%>">Post Job</a>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<section>
    <div>
        <h1>New User</h1>
        <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
        <form action="<%= users_url %>" method="post">
            <label for="user_email">Email</label>
            <input type="text"
                name="user[email]"
                id="user_email"
                value="<% @user.email %>"
            >
            <input type="password"
                name="user[password]"
                id="user_password"
                value="<% @user.password %>"
            >
            
            <input type="submit">
        </form>
    </div>
</section>

app/views/users/show.html.erb
<section>
<div>
    <h1>Your Applications</h1>
    <% @my_applied_jobs.each do |job| %>
        <h3><%= job["title"] %></h3>
        <%= job["description"] %>
    <% end %> 
    <p><a href="<%= jobs_url %>" >Back to job page<a></p>
</div>
</section>